### PR TITLE
Ria 3219 pending payment paid notification

### PR DESCRIPTION
**Pull request by bradsorour**
### JIRA link (if applicable) ###

[RIA-3219](https://tools.hmcts.net/jira/browse/RIA-3219)

### Change description ###

See Jira

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by makowalski** [comment]
depends on Business decision we will have new state or not, but that can be refactored later in there is a need. All code looks good

**Review by tarun-palisetty — DISMISSED** [review]
LGTM

**Review by Srihari-Nakkala — DISMISSED** [review]
LGTM

**Review by makowalski — APPROVED** [review]
LGTM

**Pull request merged**
